import {
  CVN_BORDER_RADIUS,
  CVN_COLOR_BG,
  CVN_COLOR_BORDER,
  CVN_COLOR_HIGHLIGHT,
  CVN_COLOR_HOVER_BG,
  CVN_COLOR_HOVER_HIGHLIGHT,
  CVN_COLOR_ICON,
  CVN_COLOR_INVERT,
  CVN_COLOR_LIGHT_ICON,
  CVN_COLOR_TEXT,
  CVN_COLOR_TEXT_DISABLED,
  CVN_DURATION_TRANSITION,
  CVN_Z_INDEX_MAX,
  CVN_Z_INDEX_POPUP,
  CVN_Z_INDEX_UNDER_POPUP,
} from '@p-lc/shared'

/**
 * 经典布局 CSS 变量
 */
export const classicalLayoutCssVars = {
  [CVN_COLOR_BG]: '#fff',
  [CVN_COLOR_TEXT]: 'rgba(0,0,0,.88)',
  [CVN_COLOR_TEXT_DISABLED]: 'rgba(0,0,0,.25)',
  [CVN_COLOR_HOVER_HIGHLIGHT]: '#4096ff',
  [CVN_COLOR_HIGHLIGHT]: '#1677ff',
  [CVN_COLOR_INVERT]: '#fff',
  [CVN_COLOR_BORDER]: 'rgba(5,5,5,.06)',
  [CVN_COLOR_ICON]: 'rgba(0,0,0,.65)',
  [CVN_COLOR_LIGHT_ICON]: 'rgba(0,0,0,.25)',
  [CVN_COLOR_HOVER_BG]: 'rgba(0,0,0,.04)',
  [CVN_DURATION_TRANSITION]: '.3s',
  [CVN_BORDER_RADIUS]: '6px',
  [CVN_Z_INDEX_MAX]: 9999,
  [CVN_Z_INDEX_POPUP]: 1000,
  [CVN_Z_INDEX_UNDER_POPUP]: 999,
}
